type IntakeFieldDefinition<Key extends string = string> = {
  key: Key;
  label: string;
  group:
    | "company"
    | "people"
    | "ai"
    | "goals"
    | "operations"
    | "infrastructure"
    | "constraints"
    | "delivery"
    | "meta";
  tier: "core" | "deepDive" | "hidden";
  input: "text" | "url" | "email" | "textarea";
  rows?: number;
  maxLength: number;
  required: boolean;
  prefillable: "yes" | "partial" | "no";
  help?: string;
};

export const INTAKE_FIELDS = [
  {
    key: "creditKey",
    label: "Payment key",
    group: "meta",
    tier: "hidden",
    input: "text",
    maxLength: 200,
    required: true,
    prefillable: "no",
  },
  {
    key: "companyName",
    label: "Company name",
    group: "company",
    tier: "core",
    input: "text",
    maxLength: 160,
    required: true,
    prefillable: "yes",
  },
  {
    key: "companyWebsite",
    label: "Company website",
    group: "company",
    tier: "core",
    input: "url",
    maxLength: 200,
    required: true,
    prefillable: "yes",
  },
  {
    key: "industry",
    label: "Industry",
    group: "company",
    tier: "core",
    input: "text",
    maxLength: 120,
    required: true,
    prefillable: "yes",
  },
  {
    key: "companyDescription",
    label: "What does your company do?",
    group: "company",
    tier: "core",
    input: "textarea",
    rows: 5,
    maxLength: 2400,
    required: true,
    prefillable: "yes",
  },
  {
    key: "businessModel",
    label: "How do you make money? (B2B / B2C / marketplace..., main revenue streams)",
    group: "company",
    tier: "core",
    input: "textarea",
    rows: 4,
    maxLength: 600,
    required: true,
    prefillable: "partial",
  },
  {
    key: "headcount",
    label: "Team size (rough breakdown by function if easy)",
    group: "company",
    tier: "core",
    input: "textarea",
    rows: 3,
    maxLength: 400,
    required: true,
    prefillable: "no",
  },
  {
    key: "productsServices",
    label: "Primary products or services you sell",
    group: "company",
    tier: "core",
    input: "textarea",
    rows: 5,
    maxLength: 1600,
    required: true,
    prefillable: "yes",
  },
  {
    key: "customerSegments",
    label: "Who your customers are (segment, size, geography)",
    group: "company",
    tier: "core",
    input: "textarea",
    rows: 4,
    maxLength: 1200,
    required: true,
    prefillable: "partial",
  },
  {
    key: "goalPrimary",
    label: "Top business goal 1",
    group: "goals",
    tier: "core",
    input: "text",
    maxLength: 220,
    required: true,
    prefillable: "no",
  },
  {
    key: "goalSecondary",
    label: "Top business goal 2",
    group: "goals",
    tier: "core",
    input: "text",
    maxLength: 220,
    required: true,
    prefillable: "no",
  },
  {
    key: "ninetyDayWin",
    label: "What a meaningful AI win looks like in the next 90 days",
    group: "goals",
    tier: "core",
    input: "textarea",
    rows: 4,
    maxLength: 1200,
    required: true,
    prefillable: "no",
  },
  {
    key: "statusQuoCost",
    label: "What the status quo is costing you (time / money / opportunity)",
    group: "goals",
    tier: "core",
    input: "textarea",
    rows: 4,
    maxLength: 1200,
    required: true,
    prefillable: "no",
  },
  {
    key: "timeConsumingWorkflows",
    label: "Which workflows consume the most time right now?",
    group: "operations",
    tier: "core",
    input: "textarea",
    rows: 6,
    maxLength: 2400,
    required: true,
    prefillable: "no",
  },
  {
    key: "currentAiUse",
    label: "Current AI use",
    group: "ai",
    tier: "core",
    input: "textarea",
    rows: 4,
    maxLength: 1600,
    required: true,
    prefillable: "no",
  },
  {
    key: "aiToolsInUse",
    label: "AI tools / subscriptions you already pay for (ChatGPT, Claude, Copilot, Gemini...)",
    group: "ai",
    tier: "core",
    input: "textarea",
    rows: 3,
    maxLength: 800,
    required: true,
    prefillable: "no",
  },
  {
    key: "pastAiAttempts",
    label: "AI attempts that stalled or failed, and why",
    group: "ai",
    tier: "core",
    input: "textarea",
    rows: 4,
    maxLength: 1600,
    required: true,
    prefillable: "no",
  },
  {
    key: "coreBusinessSystems",
    label: "Core business systems — CRM / ERP / ticketing / PM / finance / dev & engineering stack. Name them and flag which have APIs.",
    group: "infrastructure",
    tier: "core",
    input: "textarea",
    rows: 5,
    maxLength: 2000,
    required: true,
    prefillable: "partial",
  },
  {
    key: "dataLocations",
    label: "Where business data lives (spreadsheets / SaaS / DB / warehouse)",
    group: "infrastructure",
    tier: "core",
    input: "textarea",
    rows: 4,
    maxLength: 1200,
    required: true,
    prefillable: "no",
  },
  {
    key: "dataSensitivity",
    label: "Any data that must not be sent to third-party AI services (incl. regulated regimes: HIPAA / SOC 2 / GDPR...)",
    group: "constraints",
    tier: "core",
    input: "textarea",
    rows: 4,
    maxLength: 1200,
    required: true,
    prefillable: "no",
  },
  {
    key: "deliveryEmail",
    label: "Report email",
    group: "delivery",
    tier: "core",
    input: "email",
    maxLength: 180,
    required: true,
    prefillable: "no",
  },
  {
    key: "companyLinkedin",
    label: "Company LinkedIn URL",
    group: "company",
    tier: "deepDive",
    input: "url",
    maxLength: 200,
    required: false,
    prefillable: "yes",
  },
  {
    key: "goalTertiary",
    label: "Top business goal 3",
    group: "goals",
    tier: "deepDive",
    input: "text",
    maxLength: 220,
    required: false,
    prefillable: "no",
  },
  {
    key: "acquisitionChannels",
    label: "How you currently win customers (main channels)",
    group: "company",
    tier: "deepDive",
    input: "textarea",
    rows: 4,
    maxLength: 1200,
    required: false,
    prefillable: "partial",
  },
  {
    key: "competitiveDifferentiation",
    label: "Main competitors / what sets you apart",
    group: "company",
    tier: "deepDive",
    input: "textarea",
    rows: 4,
    maxLength: 1200,
    required: false,
    prefillable: "partial",
  },
  {
    key: "founderLinkedin",
    label: "Founder / owner LinkedIn URL",
    group: "people",
    tier: "deepDive",
    input: "url",
    maxLength: 200,
    required: false,
    prefillable: "no",
  },
  {
    key: "overloadedRoles",
    label: "Which roles or teams are most overloaded",
    group: "people",
    tier: "deepDive",
    input: "textarea",
    rows: 3,
    maxLength: 800,
    required: false,
    prefillable: "no",
  },
  {
    key: "technicalCapacity",
    label: "In-house technical capacity (engineers / data / IT / none)",
    group: "people",
    tier: "deepDive",
    input: "textarea",
    rows: 3,
    maxLength: 600,
    required: false,
    prefillable: "no",
  },
  {
    key: "aiSkillLevel",
    label: "Team AI skill level (none / casual / power users / built automations)",
    group: "ai",
    tier: "deepDive",
    input: "text",
    maxLength: 400,
    required: false,
    prefillable: "no",
  },
  {
    key: "repetitiveTasks",
    label: "Highest-volume repetitive tasks",
    group: "operations",
    tier: "deepDive",
    input: "textarea",
    rows: 4,
    maxLength: 1600,
    required: false,
    prefillable: "no",
  },
  {
    key: "errorProneAreas",
    label: "Where errors or rework cluster",
    group: "operations",
    tier: "deepDive",
    input: "textarea",
    rows: 4,
    maxLength: 1200,
    required: false,
    prefillable: "no",
  },
  {
    key: "workflowSample",
    label: "Paste a real example a slow workflow produces — a sample output, a redacted email thread. The single richest signal for spotting automation.",
    group: "operations",
    tier: "deepDive",
    input: "textarea",
    rows: 6,
    maxLength: 4000,
    required: false,
    prefillable: "no",
  },
  {
    key: "workflowSampleLink",
    label: "...or a link to a read-only doc / short screen recording",
    group: "operations",
    tier: "deepDive",
    input: "url",
    maxLength: 300,
    required: false,
    prefillable: "no",
  },
  {
    key: "hostingCloud",
    label: "Hosting & cloud (AWS / GCP / Azure / on-prem / none)",
    group: "infrastructure",
    tier: "deepDive",
    input: "text",
    maxLength: 600,
    required: false,
    prefillable: "partial",
  },
  {
    key: "changeConstraints",
    label: "Change-management constraints (risk-averse leadership, busy season, union...)",
    group: "constraints",
    tier: "deepDive",
    input: "textarea",
    rows: 4,
    maxLength: 1200,
    required: false,
    prefillable: "no",
  },
  {
    key: "budgetRange",
    label: "Budget range for a first AI implementation",
    group: "constraints",
    tier: "deepDive",
    input: "text",
    maxLength: 400,
    required: false,
    prefillable: "no",
  },
  {
    key: "schedulingTimezone",
    label: "Your timezone (for the consultation)",
    group: "delivery",
    tier: "deepDive",
    input: "text",
    maxLength: 80,
    required: false,
    prefillable: "no",
  },
  {
    key: "schedulingWindows",
    label: "2–3 day/time windows that usually work for the call",
    group: "delivery",
    tier: "deepDive",
    input: "textarea",
    rows: 3,
    maxLength: 400,
    required: false,
    prefillable: "no",
  },
  {
    key: "constraints",
    label: "Anything else we should know",
    group: "constraints",
    tier: "deepDive",
    input: "textarea",
    rows: 4,
    maxLength: 1600,
    required: false,
    prefillable: "no",
  },
  {
    key: "website",
    label: "Website",
    group: "meta",
    tier: "hidden",
    input: "text",
    maxLength: 120,
    required: false,
    prefillable: "no",
  },
  {
    key: "turnstileToken",
    label: "Bot protection",
    group: "meta",
    tier: "hidden",
    input: "text",
    maxLength: 2048,
    required: false,
    prefillable: "no",
  },
] as const satisfies readonly IntakeFieldDefinition[];

export type ScannerIntakeFieldKey = (typeof INTAKE_FIELDS)[number]["key"];
export type IntakeField = IntakeFieldDefinition<ScannerIntakeFieldKey>;
