import type { Metadata } from "next";
import Link from "next/link";

import { ScannerReport } from "@/components/scanner-report";
import { exampleCandidates, exampleReport } from "@/content/example-report";
import { buildPageMetadata } from "@/lib/seo";
import { rankScannerCandidates } from "@/lib/scanner-scoring";

export function generateMetadata(): Metadata {
  return buildPageMetadata({
    path: "/example",
    title: "Example Report | Oppscan",
    description:
      "See a full example AI opportunity report for a fictional business, generated by the same pipeline every paid Oppscan report uses.",
  });
}

const exampleRecord = {
  scanId: "scan_example",
  completedAt: "2026-09-18T00:00:00.000Z",
  tokenHash: "0".repeat(64),
  candidates: rankScannerCandidates(exampleCandidates),
  report: exampleReport,
};

export default function ExampleReportPage() {
  return (
    <main className="page-main">
      <section className="page-section page-section--hero">
        <div className="container page-stack">
          <p className="section-heading__eyebrow">EXAMPLE REPORT</p>
          <h1>What a $99 Oppscan report looks like</h1>
          <p>
            This is a real report from our analysis pipeline, generated for a
            fictional business (&ldquo;Redwood Fabrication Co.&rdquo; is not a
            real company) so you can see the actual depth and specificity
            before you buy. Every paid report is generated fresh for your
            business from your own intake — this is not a template filled in
            with your details.
          </p>
          <div className="scanner-price-card">
            <Link className="button button--primary" href="/">
              Get your own report — $99
            </Link>
            <Link className="button button--secondary" href="/free">
              Or try the free summary first
            </Link>
          </div>
        </div>
      </section>

      <section className="page-section">
        <div className="container">
          <ScannerReport
            ctaHelperText="This example page has no real consultation to book — this button leads to the real purchase flow."
            ctaLabel="Get your own report + consultation — $99"
            consultationHref="/"
            record={exampleRecord}
          />
        </div>
      </section>
    </main>
  );
}
